#!/bin/sh

if [ $# = 0 ]; then

    make fclean -s \
    && make -s && make clean -s \
    && gcc -o test mouli/1.c ./libmy_malloc.so \
    && LD_PRELOAD=./libmy_malloc.so ./test \
    && rm ./test

elif [ $1 = "m" ]; then

    make fclean -s \
    && make -s && make clean -s \
    && echo 'n' | LD_PRELOAD=./libmy_malloc.so ./moul_malloc_stud

else

    make fclean -s \
    && make -s && make clean -s \
    && gcc -o test mouli/$1.c ./libmy_malloc.so \
    && LD_PRELOAD=./libmy_malloc.so ./test \
    && rm ./test

fi
