#!/bin/sh

if [ $# = 0 ]; then
    make -s && make clean -s && gcc -o test mouli/1.c && LD_PRELOAD=./libmy_malloc_.so ./test && rm ./test
else
    make -s && make clean -s && gcc -o test mouli/$1.c && LD_PRELOAD=./libmy_malloc_.so ./test && rm ./test
fi
